package com.hughcode.DAO;

import com.hughcode.Alerts;
import com.hughcode.DatabaseConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class AlertsDAO { private connection conn;

    public AlertsDAO() {
        conn = DatabaseConnection.getConnection();
    }

    public void create_alert(Alerts alert) throws SQLException {

        String query = """
        INSERT INTO alerts 
        (transaction_id, rule_id, severity, reason, alert_status, created_at, solved_at)
                VALUES (?, ?, ?, ?, ?, ?)
                """;

        try (PreparedStatement stmt =
                     conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, alert.getTransactionId());
            stmt.setInt(2, alert.getRuleId());
            stmt.setString(3, alert.getSeverity());
            stmt.setString(4, alert.getReason());
            stmt.setString(5, alert.getAlertStatus());

            if (alert.getSolvedAt() != null) {
                stmt.setTimestamp(
                        6,
                        Timestamp.valueOf(alert.getSolvedAt())
                );
            } else {
                stmt.setNull(6, Types.TIMESTAMP);
            }

            stmt.executeUpdate();

            // Get the alert_id generated by MySQL
            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) {
                    return keys.getInt(1);
                }
            }
        }

        return -1;
    }

    // Get one alert by its ID
    public Alert getAlertById(int alertId) throws SQLException {

        String query = ""\"
        SELECT *
                FROM alerts
        WHERE alert_id = ?
        ""\";

        try (PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setInt(1, alertId);

            try (ResultSet rs = stmt.executeQuery()) {

                if (rs.next()) {
                    return createAlertFromResultSet(rs);
                }
            }
        }

        return null;
    }

    // Get all alerts
    public List<Alert> getAllAlerts() throws SQLException {

        String query = "SELECT * FROM alerts";

        List<Alert> alerts = new ArrayList<>();

        try (PreparedStatement stmt = conn.prepareStatement(query);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                alerts.add(createAlertFromResultSet(rs));
            }
        }

        return alerts;
    }

    // Update the status of an alert
    public void updateStatus(int alertId, String status) throws SQLException {

        String query = ""\"
        UPDATE alerts
        SET alert_status = ?
        WHERE alert_id = ?
        ""\";

        try (PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, status);
            stmt.setInt(2, alertId);

            stmt.executeUpdate();
        }
    }


}
