package com.hughcode.DAO;

import com.hughcode.Alert;
import com.hughcode.AlertForClient;
import com.hughcode.DatabaseConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class AlertsDAO {
    private Connection conn;

    public AlertsDAO() {
        conn = DatabaseConnection.getConnection();
    }

    public int create_Alert(Alert alert) throws SQLException {

        String query = """
        INSERT INTO alerts 
        (transaction_id, rule_id, severity, reason, alert_status)
                VALUES (?, ?, ?, ?, ?)
                """;

        try (PreparedStatement stmt =
                     conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, alert.getTransactionId());
            stmt.setInt(2, alert.getRuleId());
            stmt.setString(3, alert.getSeverity());
            stmt.setString(4, alert.getReason());
            stmt.setString(5, alert.getAlertStatus());

            stmt.executeUpdate();

            // Get the alert_id generated by MySQL
            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) {
                    return keys.getInt(1);
                }
            }
        }

        return -1;
    }

    // Get one alert by its ID
    public AlertForClient getAlertById(int alertId) throws SQLException {

        String query = """
        SELECT *
                FROM alerts
        WHERE alert_id = ?
        """;

        try (PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setInt(1, alertId);

            try (ResultSet rs = stmt.executeQuery()) {

                if (rs.next()) {
                    return mapResultSetToAlert(rs);
                }
            }
        }

        return null;
    }

    // Get all alerts
    public List<AlertForClient> getAllAlerts() throws SQLException {

        String query = "SELECT * FROM alerts";

        List<AlertForClient> alerts = new ArrayList<>();

        try (PreparedStatement stmt = conn.prepareStatement(query);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                alerts.add(mapResultSetToAlert(rs));
            }
        }

        return alerts;
    }

    // Update the status of an alert
    public void updateStatus(int alertId, String status) throws SQLException {

        String query = """
        UPDATE alerts
        SET alert_status = ?,
            solved_at = CASE
                WHEN UPPER(?) IN ('CLOSED', 'DISMISSED') THEN CURRENT_TIMESTAMP
                ELSE solved_at
            END
        WHERE alert_id = ?
        """;

        try (PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, status);
            stmt.setString(2, status);
            stmt.setInt(3, alertId);

            stmt.executeUpdate();
        }
    }

    private AlertForClient mapResultSetToAlert(ResultSet rs) throws SQLException{

        Timestamp solvedTimestamp = rs.getTimestamp("solved_at");
        Timestamp createdTimestamp = rs.getTimestamp("created_at");

        return new AlertForClient(
                rs.getInt("alert_id"),
                rs.getInt("rule_id"),
                rs.getString("transaction_id"),
                rs.getString("severity"),
                rs.getString("reason"),
                rs.getString("alert_status"),
                createdTimestamp.toLocalDateTime(),
                solvedTimestamp == null
                        ? null
                        : solvedTimestamp.toLocalDateTime()
        );

    }


}
